apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: sealed-secrets-lab
spec:
  encryptedData:
    foo: AgCO/7ISOW4uKoOPyXwOf2jEU47HF+JYeqPd1W1veWOTlg+InQRCdRM3jL4XLHj9D8uIhl2+oOPD3V8IMfg7KeKqJLZgvagmmvp/ih/Wh8E1VFy4ZcHlnUjHy6TRDcTIpjhehPwr8my8yui83QWLw647WLXr8MjMARSHppnKJSiucC+8L19zU8Hnan+fpEn5bmdPqsbHZYxENjuOaK2bmGNACtdlZqjYzrfL6HJxA3k8DL11kjmU58y01ReYNk2kMRBdUlHQxvqt78sznMj0q5ZdDV58r7+DH002/RTb9Gb7bcZTZ60CM3ch4af2k20r9cSbWc08zRP9EoElrExrKNcx7zYOnZNPnI1/wtTTQRyeLSMfB76HLGyNyZRVnI/ck2P/dtRCpF5IAlRXu6V8nkUdJhGDMTbiNxhkvHH24I/ZaMEOCuaaQtqKZR8FPoCEqocxAP9Y2V1ua/tkzUNyOyXNNxkG5nyeJJ3iZNO6PXxIsYlywUSWzEOwYmQ/QU9WZbfuAVud5FbW3GaqVlvIOG7ulWqACYyYg0Qjye1W+Jc0cHTJcOuZaqXBezjhWEfVDwgooRjzMFaRWrbVMOkQTBfkmuz1EIHGY+fRLleqeSyTCq63hxA2wp2mzCwZG42i/N/GGl1Eq9vSg7LH3uul59ngKiEQ9LgA+D5NBN3WR2Pwn1xdVZBtvgxN0/Z/3fytcbo4TzM=
  template:
    metadata:
      name: my-secret
      namespace: sealed-secrets-lab