apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: argo-workflows-lab
spec:
  templates:
  - name: cowsay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay, "{{inputs.parameters.message}}"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: cowsay
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: cowsay
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: cowsay
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: cowsay
        arguments:
          parameters: [{name: message, value: D}]

