apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-lab
spec:
  destination:
    namespace: argo-workflows-lab
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-workflows-lab
    repoURL: 'https://github.com/yukinakanaka/my-manifests.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false