apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-events
spec:
  destination:
    name: ''
    namespace: argo-events
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 2.4.0
    chart: argo-events
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false