apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api-app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: my-api-app
    repoURL: 'https://github.com/yukinakanaka/my-manifests.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false